"""er at trends

Revision ID: 15f2773e9ee0
Revises: c0a505f3810a
Create Date: 2026-04-19 17:28:41.828376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f2773e9ee0'
down_revision: Union[str, Sequence[str], None] = 'c0a505f3810a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('er', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trends', 'er')
    # ### end Alembic commands ###
