"""delete telegram photo value

Revision ID: 1ffda49a7f58
Revises: 70d7917469cb
Create Date: 2026-04-15 20:24:22.968065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ffda49a7f58'
down_revision: Union[str, Sequence[str], None] = '70d7917469cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'photo_id')
    op.drop_column('groups', 'photo_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('photo_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('groups', sa.Column('photo_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
