"""add ind_id to post

Revision ID: 319a1eb770b6
Revises: 74fd8d9d5d5b
Create Date: 2026-04-16 13:27:13.619131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319a1eb770b6'
down_revision: Union[str, Sequence[str], None] = '74fd8d9d5d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('industry_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_posts_industry_id'), 'posts', ['industry_id'], unique=False)
    op.create_foreign_key(None, 'posts', 'industries', ['industry_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_industry_id'), table_name='posts')
    op.drop_column('posts', 'industry_id')
    # ### end Alembic commands ###
