"""updated_at post

Revision ID: 458b8d95741e
Revises: 91d5ae2386a9
Create Date: 2026-04-17 11:43:23.664725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '458b8d95741e'
down_revision: Union[str, Sequence[str], None] = '91d5ae2386a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_trends_updated_at'), 'trends', ['updated_at'], unique=False)
    op.drop_column('trends', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_trends_updated_at'), table_name='trends')
    op.drop_column('trends', 'updated_at')
    # ### end Alembic commands ###
