"""add avatar_path

Revision ID: 4ad39ec1446d
Revises: 1ffda49a7f58
Create Date: 2026-04-15 20:41:02.241305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad39ec1446d'
down_revision: Union[str, Sequence[str], None] = '1ffda49a7f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('avatar_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'avatar_path')
    # ### end Alembic commands ###
