"""er and subscrbrs

Revision ID: 697b2ccad814
Revises: db98f36eca5c
Create Date: 2026-04-18 14:22:43.384429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697b2ccad814'
down_revision: Union[str, Sequence[str], None] = 'db98f36eca5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('subscribers', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('er', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'er')
    op.drop_column('groups', 'subscribers')
    # ### end Alembic commands ###
