"""centroid value in trends

Revision ID: 70d7917469cb
Revises: c699720f0cb0
Create Date: 2026-04-14 15:45:36.488140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = '70d7917469cb'
down_revision: Union[str, Sequence[str], None] = 'c699720f0cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('centroid', pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=True))
    op.drop_column('trends', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('trends', 'centroid')
    # ### end Alembic commands ###
