"""is_active

Revision ID: 7cc2b8559421
Revises: a38bca4f59e5
Create Date: 2026-05-08 16:18:16.508884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc2b8559421'
down_revision: Union[str, Sequence[str], None] = 'a38bca4f59e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_trends_is_active'), 'trends', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trends_is_active'), table_name='trends')
    op.drop_column('trends', 'is_active')
    # ### end Alembic commands ###
