"""add likes

Revision ID: 91d5ae2386a9
Revises: 319a1eb770b6
Create Date: 2026-04-16 22:32:27.607030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d5ae2386a9'
down_revision: Union[str, Sequence[str], None] = '319a1eb770b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('views_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'views_count')
    op.drop_column('posts', 'likes_count')
    # ### end Alembic commands ###
