"""timespan_

Revision ID: a38bca4f59e5
Revises: b5072df5ecdc
Create Date: 2026-05-07 17:10:57.649164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a38bca4f59e5'
down_revision: Union[str, Sequence[str], None] = 'b5072df5ecdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trends', sa.Column('timespan', sa.String(length=10), nullable=False))
    op.create_index(op.f('ix_trends_timespan'), 'trends', ['timespan'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trends_timespan'), table_name='trends')
    op.drop_column('trends', 'timespan')
    # ### end Alembic commands ###
